database:
  type: sqlite
  sqlite:
    file: "factions.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "piggyfactions"
  worker-limit: 1

economy:
  enabled: true
  provider: economyapi
  faction-bank:
    enabled: true

factions:
  enforce-alphanumeric-names: true
  blacklisted-names:
    - staff
    - owner
    - admin
    - mojang
    - histeria
    - dadodasyra
    - HadesSurMC
    - WillyDuGang
    - Hiroshima
    - Plutonium
  max-name-length: 16
  max-players: 20
  max-allies: 2
  pvp:
    factionless: true
    between-factionless: true
  power:
    default: 0
    min: 0
    max: 1000000000
    per:
      death: 0
      kill: 0
      hour: 0
  homes:
    within-territory: true
    teleport-on-death: false
  claims:
    whitelisted-worlds: [faction1, faction2, faction3]
    denied-commands:
      enemy: #Should we remove this ?
        - home
        - spawn
        - hub
        - lobby
        - h
      none: []
      truce: []
      ally: []
    cost: 250
    max: 200
    shield-factor: 0.1
    overclaim: true
    autoclaim: true
    unclaimall: true
    circle:
      enabled: true
      max-radius: 15
    square:
      enabled: true
      max-radius: 15

languages:
  default: "english"

symbols:
  colors:
    relations:
      member: "{GREEN}"
      ally: "{DARK_PURPLE}"
      truce: "{LIGHT_PURPLE}"
      neutral: "{WHITE}"
      enemy: "{RED}"
      safezone: "{GOLD}"
      warzone: "{DARK_RED}"
  ranks:
    leader: "*"
    officer: "^"
    member: "+"
    recruit: "-"
    none: ""
  factionless: ""
  powerless: "0"

commands:
  disabled: []

forms: true